// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT1C6wIGqK1A9uvwdqY1FborHez2BZTrA',
    appId: '1:1008343919631:web:451a85191d526154c2c77a',
    messagingSenderId: '1008343919631',
    projectId: 'art-blog-app-flutter',
    authDomain: 'art-blog-app-flutter.firebaseapp.com',
    storageBucket: 'art-blog-app-flutter.appspot.com',
    measurementId: 'G-5QQRL0BE1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATzav_9pSDCG7w0lnxq5nEfVCChfyFQZA',
    appId: '1:1008343919631:android:97935474a505eaefc2c77a',
    messagingSenderId: '1008343919631',
    projectId: 'art-blog-app-flutter',
    storageBucket: 'art-blog-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBACmtc71BiKoV0ldBWx6xm1V6JeqFg2dU',
    appId: '1:1008343919631:ios:6ca41efecc3e5a03c2c77a',
    messagingSenderId: '1008343919631',
    projectId: 'art-blog-app-flutter',
    storageBucket: 'art-blog-app-flutter.appspot.com',
    iosClientId: '1008343919631-nklp5t9rn8gsr8a6cp9rmo78gtvl6c4s.apps.googleusercontent.com',
    iosBundleId: 'com.example.artBlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBACmtc71BiKoV0ldBWx6xm1V6JeqFg2dU',
    appId: '1:1008343919631:ios:87bbf748915209b7c2c77a',
    messagingSenderId: '1008343919631',
    projectId: 'art-blog-app-flutter',
    storageBucket: 'art-blog-app-flutter.appspot.com',
    iosClientId: '1008343919631-9ie354jabu3sgrcgf9b9tofh5b2atcm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.artBlogApp.RunnerTests',
  );
}
